import schedule
import time
from datetime import datetime, date
from collections import namedtuple
import json


Camera = namedtuple("Camera", ["ip_address", "schedule"])


week = {
    "week": {
        "Monday": [
            1,
            0,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
        ],
        "Tuesday": [
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
        ],
        "Wednesday": [
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Thursday": [
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            0,
        ],
        "Friday": [
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Saturday": [
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
        ],
        "Sunday": [
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
        ],
    }
}

week2 = {
    "week": {
        "Monday": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
        ],
        "Tuesday": [
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
        ],
        "Wednesday": [
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Thursday": [
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            0,
        ],
        "Friday": [
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Saturday": [
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
        ],
        "Sunday": [
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
        ],
    }
}

week_str = json.dumps(week)

camera1 = Camera("123", week_str)
camera2 = Camera("987", json.dumps(week2))

camera_list = [camera1, camera2]


def check_schedules():
    current_time = datetime.now().strftime("%H:%M:%S")
    today = date.today()
    print("Current time:", current_time)
    weekday_str = today.strftime("%A")
    print("Weekday (str):", weekday_str)

    for camera in camera_list:
        # json_object = json.loads(camera.schedule)
        print(camera.ip_address)

        # print(json_object)


schedule.every(1).minute.do(check_schedules)


if __name__ == "__main__":
    while True:
        now = datetime.now()
        seconds_until_next_minute = 60 - now.second
        time.sleep(
            seconds_until_next_minute
        )  # Wait until the next minute starts (at :00 seconds)

        # Now run the scheduler in sync with the start of each minute
        while True:
            schedule.run_pending()
            time.sleep(1)
