import schedule
import time
from datetime import datetime, date
from collections import namedtuple
import json

# mockdata
Camera = namedtuple("Camera", ["ip_address", "schedule"])
week = {
    "week": {
        "Monday": [
            1,
            0,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
        ],
        "Tuesday": [
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
        ],
        "Wednesday": [
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Thursday": [
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            0,
        ],
        "Friday": [
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Saturday": [
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
        ],
        "Sunday": [
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
        ],
    }
}

week2 = {
    "week": {
        "Monday": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            1,
            0,
        ],
        "Tuesday": [
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
        ],
        "Wednesday": [
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
        ],
        "Thursday": [
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            1,
            0,
        ],
        "Friday": [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ],
        "Saturday": [
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
        ],
        "Sunday": [
            1,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            1,
            1,
        ],
    }
}

camera1 = Camera("123", json.dumps(week))
camera2 = Camera("987", json.dumps(week2))
camera_list = [camera1, camera2]


def check_schedules():
    current_time = datetime.now().strftime("%H:%M:%S")
    print("Current time:", current_time)
    
    today = date.today().strftime("%A")
    print("Weekday (str):", today)
    for camera in camera_list:
        schedule = json.loads(camera.schedule)
        index = datetime.now().hour
        shedule_today = schedule["week"][today]
        isSheduled =  shedule_today[index]

        if(isSheduled):
            print("ACAP should be turned ON for camera ip: " + camera.ip_address)
        else:
            print("ACAP should be turned OFF for camera ip " + camera.ip_address)

        # print(json_object)


schedule.every(1).minute.do(check_schedules)

def shedule():
    #TODO bug fix: the loop starts at each new minute, but it skips the first minute
    while True:
        seconds_until_next_minute = 60 - datetime.now().second
        print("Sleeping for: " + str(seconds_until_next_minute))
        time.sleep(
            seconds_until_next_minute
        )  # Wait until the next minute starts (at :00 seconds)

        schedule.run_pending()

if __name__ == "__main__":
    shedule()
